# Generated by Django 4.2.4 on 2023-08-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_enderecousuario_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
