# Generated by Django 4.2.4 on 2023-08-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produto_imagens/%y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promo', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variacão'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
