# Generated by Django 4.2.4 on 2023-08-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_image_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, max_length=50)),
                ('preco', models.FloatField()),
                ('preco_promo', models.FloatField(default=0)),
                ('estoque', models.PositiveSmallIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
