# Generated by Django 4.2.4 on 2023-08-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
